### ISSUE TITLE
Get to know resourcespace

### ISSUE THREAD

**Issue by emilyodean** [NBMG-UNR/resourcespace-migration#3]
The overarching project that you'll be working on for the semester is migrating our existing datasets to a content management system called ResourceSpace. I'd recommend reading through the documentation on ResourceSpace here - https://www.resourcespace.com/knowledge-base/ so that you understand objects within the system, and even create a test website to be able to log in, look at the administrative panel, figure out how to alter metadata field and upload content, etc. Another aspect of this system that we'll be using is the API. Eventually, we'll want to use the API to extract data and load it into an external PostgreSQL database, so reading up on the API (and API concepts in general) would be a good place to start. 

We have many collections of data that will be migrated into this system, and each will have different custom metadata fields. I'm planning on making a ticket under this resourcespace-migration project for each dataset. 

After you finish the above (reading through documentation, making a trial resourcespace site and playing around with it), please close this ticket, comment that you have completed the tasks, and then assign yourself to the mining district file ticket.

**Comment by lweeks20** [comment]
It's a pretty simple source to use!
