### ISSUE TITLE
Determine which metadata fields need to be included in resourcespace

### ISSUE THREAD

**Issue by emilyodean** [NBMG-UNR/resourcespace-migration#8]
We need to figure out which metadata fields are unique and which ones overlap among all the datasets on G:\datasets\. This list will be used when defining metadata fields in a new content management system that I'm configuring right now. There might be a lot of superfluous fields at the moment. I'd start by just making lists of what the current fields are for each dataset, and then looking for overlap and fields that can be removed. 

The datasets should be broadly lumped into "documents," "photos," and "physical samples." So, the result of this task should be a list like the following, where each sub-bullet inherits and expands on the list above it:

- General metadata fields
   - Document metadata fields
      - Mining district file metadata fields
      - Engineering file metadata fields
   - Photo metadata fields
      - Air photos metadata fields
   - Physical samples
      - Cores and cuttings metadata fields

e.g. 
**General**
ID
Name
Date
Latitude
Longitude

**Document**
Extracted text
Author

If you're unsure about how to categorize metadata fields, you can just make your best guess and highlight them so I know to double check.

**Comment by emilyodean** [comment]
@madsmiller please work on this when you get in today. You should now be able to sign on to the computer with your own login and access the G: drive by going through the network mapping instructions that I sent you over email when you were using David's login.

**Comment by madsmiller** [comment]
[Metadata Fields Updated.xlsx](https://github.com/NBMG-UNR/resourcespace-migration/files/4125574/Metadata.Fields.Updated.xlsx)

**Comment by madsmiller** [comment]
That last comment is a spreadsheet with my work on this project so far.

**Comment by madsmiller** [comment]
Attached is what I worked on today. 
[Metadata Fields Updated 1-30-20.xlsx](https://github.com/NBMG-UNR/resourcespace-migration/files/4136973/Metadata.Fields.Updated.1-30-20.xlsx)
[resource metadata - in progress.xlsx](https://github.com/NBMG-UNR/resourcespace-migration/files/4136977/resource.metadata.-.in.progress.xlsx)
[Categorizing datasets.docx](https://github.com/NBMG-UNR/resourcespace-migration/files/4136979/Categorizing.datasets.docx)

**Comment by emilyodean** [comment]
Hi @madsmiller, please continue working on this tomorrow. I need to be on campus, so feel free to email or call with any questions.

**Comment by madsmiller** [comment]
Will do. Thank you!

**Comment by madsmiller** [comment]
@emilyodean will do! Thank you.

**Comment by madsmiller** [comment]
[resource metadata - in progress 2.xlsx](https://github.com/NBMG-UNR/resourcespace-migration/files/4222474/resource.metadata.-.in.progress.2.xlsx)

Attached is a spreadsheet with some highlighted cells. The green represents all the metadata fields that I assume are important and should be preserved. The red represents fields that can potentially be omitted. Lastly, the white (no fill) boxes represent fields that I am unsure of their significance at the moment. If you get the chance, can you look over it and let me know which ones I incorrectly categorized and/or any that I missed? Thank you!

**Comment by emilyodean** [comment]
@madsmiller, finally had a chance to review. This is great and exactly what was needed. I'm going to go ahead and close out this ticket and we'll have you work on another task now.
